export const SymbolToName: { [key: string]: string } = {
	BKN: "Bekhnam",
	USDB: "Bekhnam USD",
	BTC: "Bitcoin",
	ETH: "Ethereum",
	WETH: "Wrapped ethereum",
	BNB: "Binance",
	USDT: "Tether",
	USDC: "USD Coin",
	ADA: "Cardano",
	SOL: "Solana",
	AVAX: "Avalanche",
	BUSD: "Binance USD",
	MATIC: "Polygon",
	DAI: "Dai",
};
